//! Emits constants generated at host time:
//!
//!   - `LED_PWM_FREQ_HZ`           — carrier frequency for the LED PWM
//!   - `MIDI_NOTE_HZ: [u32; 128]`  — frequency of each MIDI note number,
//!                                   precomputed in f32 from `440 × 2^((n-69)/12)`

use std::fs::write;
use std::path::PathBuf;

const LED_PWM_FREQ_HZ: u32 = 1_000;

fn main() {
    let mut s = String::from("// AUTO-GENERATED by build.rs. Do not edit.\n\n");
    s.push_str(&format!("pub const LED_PWM_FREQ_HZ: u32 = {};\n\n", LED_PWM_FREQ_HZ));

    // MIDI standard: note 69 = A4 = 440 Hz; semitone = 12th root of 2.
    s.push_str("pub static MIDI_NOTE_HZ: [u32; 128] = [\n");
    for n in 0..128u32 {
        let freq = 440.0_f32 * 2f32.powf((n as f32 - 69.0) / 12.0);
        let hz = freq.round() as u32;
        if n % 8 == 0 {
            s.push_str("    ");
        }
        s.push_str(&format!("{:5}, ", hz));
        if n % 8 == 7 {
            s.push('\n');
        }
    }
    s.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    write(PathBuf::from(out_dir).join("lut.rs"), s).expect("failed to write lut.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
