//! Generates a gamma-corrected sine LUT at build time and emits it as a
//! `static` array so it lives in Flash (`.rodata`), not RAM.
//!
//! Runs on the *host* (Windows), so we can freely use `f32::sin` / `f32::powf`
//! from std — the embedded target only sees the resulting `[u16; N]` literal.

use std::f32::consts::PI;
use std::fs::write;
use std::path::PathBuf;

// Must match the clock embassy_stm32::init(Default::default()) gives us:
// HSI 16 MHz, APB2 prescaler = 1 → TIM1 clock = 16 MHz.
// If you switch to HSE+PLL later, update this number (or read it from build env).
const TIMER_CLK_HZ: u32 = 16_000_000;
const PWM_FREQ_HZ: u32 = 1_000;
const LUT_LEN: usize = 2048;
const GAMMA: f32 = 2.2;

fn main() {
    // Replicate embassy's set_frequency_internal() algorithm so we know the
    // exact ARR the timer will use at runtime — the LUT must scale to that.
    let ticks_per_period = TIMER_CLK_HZ / PWM_FREQ_HZ;
    let psc = (ticks_per_period - 1) / 65_536;
    let divide_by = ticks_per_period / (psc + 1);
    let pwm_top: u16 = divide_by as u16; // max_duty_cycle() = ARR + 1 = divide_by

    let mut s = String::new();
    s.push_str("// AUTO-GENERATED by build.rs. Do not edit.\n");
    s.push_str(&format!("pub const LUT_LEN: usize = {};\n", LUT_LEN));
    s.push_str(&format!("pub const PWM_FREQ_HZ: u32 = {};\n", PWM_FREQ_HZ));
    s.push_str(&format!("pub const PWM_TOP: u16 = {};\n", pwm_top));
    s.push_str(&format!(
        "pub static DUTY_LUT: [u16; LUT_LEN] = [\n"
    ));

    let top = pwm_top as f32;
    for i in 0..LUT_LEN {
        let phase = i as f32 * 2.0 * PI / LUT_LEN as f32;
        let normalized = (phase.sin() + 1.0) * 0.5;
        let perceptual = normalized.powf(GAMMA);
        let duty = (perceptual * top) as u16;
        // 8 values per line for readability
        if i % 8 == 0 {
            s.push_str("    ");
        }
        s.push_str(&format!("{}, ", duty));
        if i % 8 == 7 {
            s.push('\n');
        }
    }
    s.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set by cargo");
    let path = PathBuf::from(out_dir).join("lut.rs");
    write(&path, s).expect("failed to write generated lut.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
