//! Emits the LED PWM frequency constant into OUT_DIR/lut.rs so light_show.rs
//! can include it. (Historically this file also baked a gamma-corrected sine
//! LUT for breathing LED into Flash, but the LED is now driven directly by
//! music events and no longer needs an LUT.)

use std::fs::write;
use std::path::PathBuf;

const LED_PWM_FREQ_HZ: u32 = 1_000;

fn main() {
    let mut s = String::from("// AUTO-GENERATED by build.rs. Do not edit.\n\n");
    s.push_str(&format!("pub const LED_PWM_FREQ_HZ: u32 = {};\n", LED_PWM_FREQ_HZ));

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    write(PathBuf::from(out_dir).join("lut.rs"), s).expect("failed to write lut.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
